version: '3.1'

services:

    nginx:
        container_name: at-nginx
        build:
            context: docker/config/nginx
        ports:
            - 8000:80
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        container_name: at-php
        build:
            context: docker/config/php
        ports:
            - 9000:9000
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/config/php/php.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
